### ISSUE TITLE
cant delete project 

### ISSUE THREAD

**Issue by pythoniaweb** [Just-Msv/Uptimer-Bot#2]
i get a error 
````
/home/container/node_modules/mongoose/lib/helpers/query/wrapThunk.js:21
      const err = new MongooseError('Query was already executed: ' + str);
                  ^

MongooseError: Query was already executed: Uptime.find({ link: 'https://www.bondomusic.ga/' })
    at model.Query._wrappedThunk [as _find] (/home/container/node_modules/mongoose/lib/helpers/query/wrapThunk.js:21:19)
    at /home/container/node_modules/kareem/index.js:367:25
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  originalStack: 'Error\n' +
    '    at model.Query._wrappedThunk [as _find] (/home/container/node_modules/mongoose/lib/helpers/query/wrapThunk.js:25:28)\n' +
    '    at /home/container/node_modules/kareem/index.js:367:25\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:78:11)'
}
````

**Comment by noob04coder** [comment]
I fixed this error by using an older version of mongoose (which is v5) , you can change the version for mongoose in package.json

**Comment by pythoniaweb** [comment]
Thanks
